export {default as Dashboard} from './dashboard/Dashboard';
export {default as Reservations} from './reservation/Reservations'
export {default as Detail} from './reservation/Detail';
export {default as AddRoomType} from './room-type/AddRoomType';
export {default as EditRoomType} from './room-type/EditRoomType';
export {default as RoomType} from './room-type/RoomType';
export {default as AddRoom} from './rooms/AddRoom';
export {default as AllRooms} from './rooms/AllRooms';
export {default as OccupiedRooms} from './occupancy/OccupiedRooms';
export {default as OccupationHistory} from './occupancy/OccupationHistory';
export {default as Login} from './Login';
export {default as ResetPwd} from './ResetPassword';
export {default as ChangePwd} from './ChangePassword';